import React, { useEffect, useState } from 'react';
import { Edit3, FolderPlus, Inbox, Pencil, Tags, Trash2, X } from 'lucide-react';
import { useStore } from '../store/useStore';

type Category = { id: number; name: string; type: 'income' | 'expense' | 'both'; transaction_count: number; total_amount: number; last_used?: string | null };
const currency = new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 });
const card = (advanced: boolean) => advanced ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-100';
const field = (advanced: boolean) => `w-full rounded-xl border px-3 py-2.5 text-sm outline-none ${advanced ? 'bg-slate-900 border-slate-700 focus:border-violet-500' : 'bg-slate-50 border-slate-200 focus:border-emerald-500'}`;

export function Categories() {
  const { themeMode, shouldRefresh, triggerRefresh } = useStore();
  const advanced = themeMode === 'advanced';
  const [categories, setCategories] = useState<Category[]>([]);
  const [editor, setEditor] = useState<Category | 'new' | null>(null);
  const load = async () => { const response = await fetch('/api/categories'); if (response.ok) setCategories(await response.json()); };
  useEffect(() => { load().catch(console.error); }, [shouldRefresh]);
  const save = async (values: { name: string; type: string }) => {
    const editing = editor && editor !== 'new' ? editor : null;
    const response = await fetch(editing ? `/api/categories/${editing.id}` : '/api/categories', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) });
    if (!response.ok) return; setEditor(null); triggerRefresh(); await load();
  };
  const archive = async (category: Category) => {
    if (!window.confirm(`Archive ${category.name}? It will stay on historic transactions but no longer appear as a suggested category.`)) return;
    const response = await fetch(`/api/categories/${category.id}`, { method: 'DELETE' });
    if (response.ok) { triggerRefresh(); await load(); }
  };
  const income = categories.filter(category => category.type === 'income' || category.type === 'both');
  const expenses = categories.filter(category => category.type === 'expense' || category.type === 'both');
  return <div className="space-y-6 pb-10">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold">Categories</h2><p className="mt-1 text-slate-500">Your personal income and expense taxonomy. A category is added automatically whenever you save a new one on a transaction.</p></div><button onClick={() => setEditor('new')} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}><FolderPlus size={16} /> Add category</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Stat advanced={advanced} label="Active categories" value={String(categories.length)} /><Stat advanced={advanced} label="Income categories" value={String(income.length)} tone="emerald" /><Stat advanced={advanced} label="Expense categories" value={String(expenses.length)} tone="rose" /></div>
    {categories.length ? <div className="grid gap-6 xl:grid-cols-2"><CategoryGroup advanced={advanced} title="Income" categories={income} onEdit={setEditor} onArchive={archive} /><CategoryGroup advanced={advanced} title="Expenses" categories={expenses} onEdit={setEditor} onArchive={archive} /></div> : <div className={`rounded-3xl border border-dashed p-12 text-center ${advanced ? 'border-slate-700 bg-slate-800/50' : 'border-slate-200 bg-white/70'}`}><div className={`mx-auto mb-4 w-fit rounded-2xl p-4 ${advanced ? 'bg-slate-800 text-violet-300' : 'bg-slate-50 text-slate-500'}`}><Tags size={28} /></div><h3 className="font-bold">No categories yet</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Create one here, or record an income or expense from an account. Its category is saved automatically and will appear here.</p><button onClick={() => setEditor('new')} className={`mt-5 inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}><FolderPlus size={16} /> Add category</button></div>}
    {editor && <CategoryModal advanced={advanced} category={editor === 'new' ? null : editor} onClose={() => setEditor(null)} onSave={save} />}
  </div>;
}

function Stat({ advanced, label, value, tone = 'violet' }: { advanced: boolean; label: string; value: string; tone?: string }) { const colors: Record<string, string> = { emerald: 'text-emerald-600 dark:text-emerald-300', rose: 'text-rose-600 dark:text-rose-300', violet: 'text-violet-600 dark:text-violet-300' }; return <div className={`rounded-3xl border p-5 ${card(advanced)}`}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${colors[tone]}`}>{value}</p></div>; }
function CategoryGroup({ advanced, title, categories, onEdit, onArchive }: { advanced: boolean; title: string; categories: Category[]; onEdit: (category: Category) => void; onArchive: (category: Category) => void }) { return <div className={`rounded-3xl border p-6 ${card(advanced)}`}><h3 className="font-bold">{title}</h3><div className="mt-4 space-y-3">{categories.length ? categories.map(category => <div key={category.id} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-slate-900/50"><div className="min-w-0"><p className="font-bold">{category.name}</p><p className="mt-1 text-xs text-slate-500">{category.transaction_count} transaction{category.transaction_count === 1 ? '' : 's'}{category.last_used ? ` · Last used ${category.last_used}` : ''}</p></div><div className="flex items-center gap-2"><p className="hidden text-sm font-bold sm:block">{currency.format(category.total_amount || 0)}</p><button aria-label={`Edit ${category.name}`} onClick={() => onEdit(category)} className="rounded-lg p-2 hover:bg-slate-200 dark:hover:bg-slate-700"><Pencil size={15} /></button><button aria-label={`Archive ${category.name}`} onClick={() => onArchive(category)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 size={15} /></button></div></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-900/50">No {title.toLowerCase()} categories yet.</p>}</div></div>; }
function CategoryModal({ advanced, category, onClose, onSave }: { advanced: boolean; category: Category | null; onClose: () => void; onSave: (values: { name: string; type: string }) => void }) { const [name, setName] = useState(category?.name || ''); const [type, setType] = useState(category?.type === 'both' ? 'expense' : category?.type || 'expense'); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-label={category ? 'Edit category' : 'Add category'} onMouseDown={event => event.stopPropagation()} className={`w-full max-w-md rounded-3xl border p-6 shadow-2xl ${card(advanced)}`}><div className="mb-5 flex items-center justify-between"><h3 className="text-xl font-bold">{category ? 'Edit category' : 'Add category'}</h3><button aria-label="Close" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700"><X size={18} /></button></div><label className="block text-sm font-bold">Category name<input autoFocus value={name} onChange={event => setName(event.target.value)} className={`${field(advanced)} mt-1.5`} placeholder="e.g. Groceries, Salary, Transport" /></label><label className="mt-4 block text-sm font-bold">Used for<select value={type} onChange={event => setType(event.target.value)} className={`${field(advanced)} mt-1.5`}><option value="expense">Expenses</option><option value="income">Income</option></select></label><button disabled={!name.trim()} onClick={() => onSave({ name: name.trim(), type })} className={`mt-5 w-full rounded-xl py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}>{category ? 'Save changes' : 'Add category'}</button></div></div>; }
