import React, { useEffect, useMemo, useState } from 'react';
import { Check, ClipboardList, Edit3, FileText, Plus, Trash2, X } from 'lucide-react';
import { useStore } from '../store/useStore';

type Note = { id: number; title: string; body: string; updated_at: string };
type Routine = { id: number; name: string; frequency: string; completed_today: number; completed_this_week: number };
const card = (advanced: boolean) => advanced ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-100';
const field = (advanced: boolean) => `w-full rounded-xl border px-3 py-2.5 text-sm outline-none ${advanced ? 'bg-slate-900 border-slate-700 focus:border-violet-500' : 'bg-slate-50 border-slate-200 focus:border-emerald-500'}`;

export function Personal({ category }: { category?: string }) {
  const { themeMode } = useStore(); const advanced = themeMode === 'advanced';
  const [notes, setNotes] = useState<Note[]>([]); const [routines, setRoutines] = useState<Routine[]>([]);
  const [noteEditor, setNoteEditor] = useState<Note | 'new' | null>(null); const [routineEditor, setRoutineEditor] = useState<Routine | 'new' | null>(null);
  const load = async () => { const [noteResponse, routineResponse] = await Promise.all([fetch('/api/personal/notes'), fetch('/api/personal/routines')]); if (noteResponse.ok) setNotes(await noteResponse.json()); if (routineResponse.ok) setRoutines(await routineResponse.json()); };
  useEffect(() => { load().catch(console.error); }, []);
  const saveNote = async (values: Pick<Note, 'title' | 'body'>) => { const editing = noteEditor && noteEditor !== 'new' ? noteEditor : null; const response = await fetch(editing ? `/api/personal/notes/${editing.id}` : '/api/personal/notes', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); if (response.ok) { setNoteEditor(null); await load(); } };
  const deleteNote = async (note: Note) => { if (!window.confirm(`Delete ${note.title}?`)) return; if ((await fetch(`/api/personal/notes/${note.id}`, { method: 'DELETE' })).ok) await load(); };
  const saveRoutine = async (values: Pick<Routine, 'name' | 'frequency'>) => { const editing = routineEditor && routineEditor !== 'new' ? routineEditor : null; const response = await fetch(editing ? `/api/personal/routines/${editing.id}` : '/api/personal/routines', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); if (response.ok) { setRoutineEditor(null); await load(); } };
  const deleteRoutine = async (routine: Routine) => { if (!window.confirm(`Delete ${routine.name}?`)) return; if ((await fetch(`/api/personal/routines/${routine.id}`, { method: 'DELETE' })).ok) await load(); };
  const checkIn = async (routine: Routine) => { if ((await fetch(`/api/personal/routines/${routine.id}/check-in`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) })).ok) await load(); };
  const completed = routines.filter(routine => Boolean(routine.completed_today)).length;
  const view = category || 'overview';

  if (view === 'notes') return <PersonalNotes advanced={advanced} notes={notes} onAdd={() => setNoteEditor('new')} onEdit={setNoteEditor} onDelete={deleteNote} editor={noteEditor} setEditor={setNoteEditor} onSave={saveNote} />;
  if (view === 'routines') return <PersonalRoutines advanced={advanced} routines={routines} onAdd={() => setRoutineEditor('new')} onEdit={setRoutineEditor} onDelete={deleteRoutine} onCheck={checkIn} editor={routineEditor} setEditor={setRoutineEditor} onSave={saveRoutine} />;
  return <div className="space-y-6 pb-10"><div><h2 className="text-2xl font-bold">Personal Space</h2><p className="mt-1 text-slate-500">A private place for the small things that support your financial, career, and business plans.</p></div><div className="grid gap-4 sm:grid-cols-3"><Stat advanced={advanced} label="Notes" value={String(notes.length)} /><Stat advanced={advanced} label="Active routines" value={String(routines.length)} /><Stat advanced={advanced} label="Completed today" value={`${completed}/${routines.length}`} tone="emerald" /></div><div className="grid gap-6 lg:grid-cols-2"><Section advanced={advanced} icon={FileText} title="Notes" description="Keep personal ideas, reminders, and reference notes out of your financial records." action={() => setNoteEditor('new')} actionLabel="New note">{notes.length ? notes.slice(0, 4).map(note => <div key={note.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900/50"><p className="font-bold">{note.title}</p><p className="mt-1 line-clamp-2 text-sm text-slate-500">{note.body || 'No content yet'}</p></div>) : <Empty text="No notes yet." />}</Section><Section advanced={advanced} icon={ClipboardList} title="Routines" description="Create a simple daily or weekly routine, then check it off when it is done." action={() => setRoutineEditor('new')} actionLabel="New routine">{routines.length ? routines.slice(0, 4).map(routine => <button key={routine.id} onClick={() => checkIn(routine)} className="flex w-full items-center justify-between rounded-xl bg-slate-50 p-3 text-left hover:bg-slate-100 dark:bg-slate-900/50 dark:hover:bg-slate-700"><span><span className="block font-bold">{routine.name}</span><span className="text-xs text-slate-500">{routine.frequency} · {routine.completed_this_week}/7 this week</span></span><span className={`rounded-full p-2 ${routine.completed_today ? 'bg-emerald-500 text-white' : 'bg-slate-200 text-slate-500 dark:bg-slate-700'}`}><Check size={15} /></span></button>) : <Empty text="No routines yet." />}</Section></div>{noteEditor && <NoteModal advanced={advanced} note={noteEditor === 'new' ? null : noteEditor} onClose={() => setNoteEditor(null)} onSave={saveNote} />}{routineEditor && <RoutineModal advanced={advanced} routine={routineEditor === 'new' ? null : routineEditor} onClose={() => setRoutineEditor(null)} onSave={saveRoutine} />}</div>;
}

function PersonalNotes({ advanced, notes, onAdd, onEdit, onDelete, editor, setEditor, onSave }: any) { return <div className="space-y-6 pb-10"><Header title="Personal Notes" text="Notes are private, standalone records and do not affect your finances." action={onAdd} actionLabel="New note" advanced={advanced} />{notes.length ? <div className="grid gap-4 lg:grid-cols-2">{notes.map((note: Note) => <div key={note.id} className={`rounded-3xl border p-5 ${card(advanced)}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{note.title}</h3><p className="mt-1 text-xs text-slate-500">Updated {String(note.updated_at).replace('T', ' ').slice(0, 16)}</p></div><div className="flex gap-1"><button aria-label={`Edit ${note.title}`} onClick={() => onEdit(note)} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-700"><Edit3 size={15} /></button><button aria-label={`Delete ${note.title}`} onClick={() => onDelete(note)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 size={15} /></button></div></div><p className="mt-4 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{note.body || 'No content yet.'}</p></div>)}</div> : <EmptyPanel advanced={advanced} icon={FileText} text="Create your first personal note." action={onAdd} />}{editor && <NoteModal advanced={advanced} note={editor === 'new' ? null : editor} onClose={() => setEditor(null)} onSave={onSave} />}</div>; }
function PersonalRoutines({ advanced, routines, onAdd, onEdit, onDelete, onCheck, editor, setEditor, onSave }: any) { return <div className="space-y-6 pb-10"><Header title="Routines" text="Simple repeatable habits with a daily check-in and a seven-day completion view." action={onAdd} actionLabel="New routine" advanced={advanced} />{routines.length ? <div className="grid gap-4 lg:grid-cols-2">{routines.map((routine: Routine) => <div key={routine.id} className={`rounded-3xl border p-5 ${card(advanced)}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{routine.name}</h3><p className="mt-1 text-sm text-slate-500">{routine.frequency} · {routine.completed_this_week}/7 check-ins this week</p></div><div className="flex gap-1"><button aria-label={`Edit ${routine.name}`} onClick={() => onEdit(routine)} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-700"><Edit3 size={15} /></button><button aria-label={`Delete ${routine.name}`} onClick={() => onDelete(routine)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 size={15} /></button></div></div><button onClick={() => onCheck(routine)} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold ${routine.completed_today ? 'bg-emerald-500 text-white hover:bg-emerald-600' : advanced ? 'bg-slate-700 hover:bg-slate-600' : 'bg-slate-100 hover:bg-slate-200'}`}><Check size={16} /> {routine.completed_today ? 'Completed today' : 'Check in today'}</button></div>)}</div> : <EmptyPanel advanced={advanced} icon={ClipboardList} text="Create a routine to begin checking in." action={onAdd} />}{editor && <RoutineModal advanced={advanced} routine={editor === 'new' ? null : editor} onClose={() => setEditor(null)} onSave={onSave} />}</div>; }
function Header({ title, text, action, actionLabel, advanced }: any) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-slate-500">{text}</p></div><button onClick={action} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-white ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}><Plus size={16} /> {actionLabel}</button></div>; }
function Stat({ advanced, label, value, tone = 'violet' }: any) { return <div className={`rounded-3xl border p-5 ${card(advanced)}`}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${tone === 'emerald' ? 'text-emerald-600 dark:text-emerald-300' : 'text-violet-600 dark:text-violet-300'}`}>{value}</p></div>; }
function Section({ advanced, icon: Icon, title, description, action, actionLabel, children }: any) { return <div className={`rounded-3xl border p-6 ${card(advanced)}`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`rounded-2xl p-3 ${advanced ? 'bg-violet-500/10 text-violet-300' : 'bg-emerald-50 text-emerald-600'}`}><Icon size={20} /></div><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div></div><button onClick={action} aria-label={actionLabel} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-700"><Plus size={18} /></button></div><div className="mt-5 space-y-3">{children}</div></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-900/50">{text}</p>; }
function EmptyPanel({ advanced, icon: Icon, text, action }: any) { return <div className={`rounded-3xl border border-dashed p-12 text-center ${advanced ? 'border-slate-700 bg-slate-800/50' : 'border-slate-200 bg-white/70'}`}><Icon className="mx-auto text-slate-400" size={30} /><p className="mt-3 text-sm text-slate-500">{text}</p><button onClick={action} className={`mt-4 rounded-xl px-4 py-2.5 text-sm font-bold text-white ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}><Plus size={15} className="mr-1 inline" /> Add</button></div>; }
function NoteModal({ advanced, note, onClose, onSave }: any) { const [form, setForm] = useState({ title: note?.title || '', body: note?.body || '' }); return <Modal advanced={advanced} title={note ? 'Edit note' : 'New note'} onClose={onClose}><label className="block text-sm font-bold">Title<input autoFocus value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className={`${field(advanced)} mt-1.5`} /></label><label className="mt-4 block text-sm font-bold">Note<textarea rows={7} value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} className={`${field(advanced)} mt-1.5 resize-none`} /></label><button disabled={!form.title.trim()} onClick={() => onSave({ title: form.title.trim(), body: form.body })} className={`mt-5 w-full rounded-xl py-3 text-sm font-bold text-white disabled:opacity-50 ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}>Save note</button></Modal>; }
function RoutineModal({ advanced, routine, onClose, onSave }: any) { const [form, setForm] = useState({ name: routine?.name || '', frequency: routine?.frequency || 'Daily' }); return <Modal advanced={advanced} title={routine ? 'Edit routine' : 'New routine'} onClose={onClose}><label className="block text-sm font-bold">Routine name<input autoFocus value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className={`${field(advanced)} mt-1.5`} placeholder="e.g. Morning walk" /></label><label className="mt-4 block text-sm font-bold">Frequency<select value={form.frequency} onChange={event => setForm({ ...form, frequency: event.target.value })} className={`${field(advanced)} mt-1.5`}><option>Daily</option><option>Weekdays</option><option>Weekly</option></select></label><button disabled={!form.name.trim()} onClick={() => onSave({ name: form.name.trim(), frequency: form.frequency })} className={`mt-5 w-full rounded-xl py-3 text-sm font-bold text-white disabled:opacity-50 ${advanced ? 'bg-violet-600 hover:bg-violet-700' : 'bg-slate-900 hover:bg-slate-800'}`}>Save routine</button></Modal>; }
function Modal({ advanced, title, onClose, children }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event: React.MouseEvent) => event.stopPropagation()} className={`w-full max-w-lg rounded-3xl border p-6 shadow-2xl ${card(advanced)}`}><div className="mb-5 flex items-center justify-between"><h3 className="text-xl font-bold">{title}</h3><button aria-label="Close" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700"><X size={18} /></button></div>{children}</div></div>; }
